### ISSUE TITLE
Why not simply set the placeholder in "userland" ?

### ISSUE THREAD

**Issue by mikob** [TarekRaafat/autoComplete.js#10]
I see there's a setting for placeholder. But it doesn't seem to do anything special. Why not just allow developers to set the placeholder text in their html?

**Comment by mikob** [comment]
Actually the way it stands the js placeholder code overwrites any placeholder set in the html even if you don't use the setting. I think it's best to just remove it as it's unnecessary.

**Comment by TarekRaafat** [comment]
That's true just checked and it does overwrite any placeholder which is not proper, I will fix it in order not to do so.

autoComplete.js is a "Use Case Design Driven" so every function has a use case and a reason behind it, that's why I have to find a good reason or more common use case to remove it. I understand that you find it necessary but others might do, fixing it will allow you to just neglect it without worrying about it.

**Comment by mikob** [comment]
@TarekRaafat I think it's best to keep a design minimal, personally. Since placeholder is just one of many attributes of a text input, why stop there? Why not add settings for `maxlength`, `required` etc. ? Since the attribute is just a 1:1 mapping, I think it's best not to include it at all. Actually, having it confused me because I was unsure whether my placeholder set in the html would still work (and it will likely confuse others).

Since calling `ele.placeholder` has exactly the same effect (even working the same way internally). There should be no use case that is not covered by doing the placeholder outside of it.

FWIW, this popular existing library doesn't include placeholder either: https://goodies.pixabay.com/javascript/auto-complete/demo.html

**Comment by TarekRaafat** [comment]
@mikob check v2.1.0 just released and it has fixed the placeholder overwriting bug.
You have a valid point about removing the placeholder, will consider it.
