### ISSUE TITLE
Hide result container if no options presented

### ISSUE THREAD

**Issue by digiiitalmb** [TarekRaafat/autoComplete.js#100]
Hi there,

At the moment you can't have any styles on results container because it's always visible and there is no class or anything to indicate whether result container has some results.

I would suggest adding .no-results and .has-results classes to at least you would have some control over css.

**Comment by adriandmitroca** [comment]
For the time being, you can use workaround: `.autoComplete-list:empty { display: none }`

**Comment by TarekRaafat** [comment]
Hello @digiiitalmb and @adriandmitroca,

I understand how that behavior been kind of inconvenient for some people. That's why I've changed it already in the coming release [v8.0.0](https://github.com/TarekRaafat/autoComplete.js/tree/v8.0.0).

@adriandmitroca, thanks for sharing your workaround!


Have a nice day, guys. Cheers! :)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
