### ISSUE TITLE
[question] Callback on suggestion list item focus (not selection)

### ISSUE THREAD

**Issue by alexryndin** [TarekRaafat/autoComplete.js#103]
Hello.
I went through issues and didn't find anything appropriate. What I want is a google.com-like input field where you go through suggestions and that suggestion appears in the input field (maybe through callback call). Is it possible with the current version or "Add event emitters for navigation" is the feature I should wait for (or implement myself :))?

**Comment by TarekRaafat** [comment]
Hello @alexryndin,

If I got you right, then probably you're referring to an `inline suggestion` feature as per this issue #55.

Unfortunately, `inline suggestion` is not going to be implemented anytime soon. Since it could be developed as an external plugin for the `autoComplete.js` library without overloading it and forcing such a function on users who wouldn't need it.

So, I highly encourage you to develop the `inline suggestion` feature/function as a standalone plugin for the library, if you're interested and I'll gladly be helping you out with it as much as possible.

Cheers, have a good one! :)

**Comment by alexryndin** [comment]
@TarekRaafat Hello!
I've solved my problem by implementing custom navigation function. It's mostly based on default navigation function, but on every up/down keypress I change text in the input field. Thanks!

**Comment by NYDrewReynolds** [comment]
hey @alexryndin, I am struggling to create something similar on my end. Could you provide the navigation function you came up with?

**Comment by alexryndin** [comment]
@NYDrewReynolds here is the default navigation function -- https://github.com/TarekRaafat/autoComplete.js/blob/master/src/views/autoCompleteView.js#L120
I just copy-cat that, and since my was to update text field after every event, I just added corresponding action on every keys.ARROW_DOWN keys.ARROW_UP etc. So you can wrap navigation function and add corresponding actions you want to achieve.

**Comment by NYDrewReynolds** [comment]
Super helpful, thanks @alexryndin!

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
