### ISSUE TITLE
Close results list programatically

### ISSUE THREAD

**Issue by eballeste** [TarekRaafat/autoComplete.js#105]
Would love to see a way to trigger the autocomplete results list to hide until a user starts typing into the input field again.

**Comment by PhantomWatson** [comment]
Related to this, I think that most users would expect autoComplete.js to function similarly to the `<select>` element, in that once it's "open" (results are being displayed), any click anywhere in the browser results in the results list closing. The current release appears to require the user to select a search result to remove the results list, which is awkward for users who might start typing in an input field, then change their mind, then they're stuck with a floating thing that they don't want to interact with and which doesn't close in any intuitive way.

In lieu of a built-in "close the results list when the user clicks" configuration option, my solution was this:

### Having the results list automatically close upon any click
```javascript
new autoComplete({
    ...
    resultsList: {
        container: source => {
            source.setAttribute('id', 'autoComplete_list');
            document.getElementById('autoComplete').addEventListener('autoComplete', function (event) {
                function hideSearchResults() {
                    const searchResults = document.getElementById('autoComplete_list');
                    while (searchResults.firstChild) {
                        searchResults.removeChild(searchResults.firstChild);
                    }
                    document.removeEventListener('click', hideSearchResults);
                }
                document.addEventListener('click', hideSearchResults);
            })
        },
    }
    ...
});
```

### Sidenotes:
 - For some reason, `searchResults.innerHtml = ''` had no effect despite it being the method that autoComplete.js uses to clear the results, so I used that `while` loop instead. 🤷‍♂️
 - This awkward method of creating a one-time event listener can be replaced with a simple `{once: true}` parameter dropped into `addEventListener()` [once Internet Explorer gets around to supporting it](https://caniuse.com/#feat=once-event-listener).

**Comment by TarekRaafat** [comment]
Hello @eballeste and @PhantomWatson,

I understand how that behavior been kind of inconvenient for some people. That's why I've changed it already in the coming release [v8.0.0](https://github.com/TarekRaafat/autoComplete.js/tree/v8.0.0).

@PhantomWatson, thanks for sharing your workaround!


Have a nice day guys. Cheers! :)

**Comment by CodeWithOz** [comment]
@TarekRaafat I upgraded to `v8.0.0` and got this error: `ReferenceError: autoComplete is not defined`. It appears that the `autoComplete` constructor has been replaced with `autoCompleteJS`. Are there any other breaking changes we should be aware of if we want to use that release immediately? Or will it be better to just wait until it's released? Thanks!

**Comment by TarekRaafat** [comment]
Hello @CodeWithOz,

- That's correct the new constructor in `v8.0.0.0` is `autoCompleteJS`.
> Do you prefer the old constructor name?

- There are few other breaking changes that I don't recall them all right now but off the top of my head, the `eventEmitters` names changed. 
> I will make sure to add asap pre-release information on `v8.0.0.0` for users who are going to be using it.

- I would advise you to avoid the risk of using the pre-release of `v8.0.0.0` in production, yet I would love it if you could use it because your feedback would be very helpful and of course I will be supporting the pre-release users.


Hope that was helpful.

Have a nice day, cheers! :)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
