### ISSUE TITLE
Explain styling options in docs

### ISSUE THREAD

**Issue by nhaberl** [TarekRaafat/autoComplete.js#109]
You autocomplete looks good but are there any docs how to style it the way it fits to the respective design ? Would be helpful or better to set in the options

Thanks for this nice plugin

**Comment by TarekRaafat** [comment]
Hello @nhaberl,


```js
```

**Comment by TarekRaafat** [comment]
Hello @nhaberl,

I'm glad that `autoComplete.js` came in handy for you.

The below code shows how to set custom class/id for the results list and each result item as well since both are the only elements implicitly set. Regarding the input field itself should not be a big deal because you create it and the "no results" element customization is shown in this link [codepen](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010)

```js
resultsList: {
    render: true,
    container: source => {
        source.setAttribute("class", "custom");
    }
},
resultItem: {
    content: (data, source) => {
        source.setAttribute("class", "custom");
    }
}
```

Hope that helps, please try it and let me know if it worked as expected or not.

Cheers, good day! :)

**Comment by sorxrob** [comment]
> Hello @nhaberl,
> 
> I'm glad that `autoComplete.js` came in handy for you.
> 
> The below code shows how to set custom class/id for the results list and each result item as well since both are the only elements implicitly set. Regarding the input field itself should not be a big deal because you create it and the "no results" element customization is shown in this link [codepen](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010)
> 
> ```js
> resultsList: {
>     render: true,
>     container: source => {
>         source.setAttribute("class", "custom");
>     }
> },
> resultItem: {
>     content: (data, source) => {
>         source.setAttribute("class", "custom");
>     }
> }
> ```
> 
> Hope that helps, please try it and let me know if it worked as expected or not.
> 
> Cheers, good day! :)

Thanks for this! How about styling the input itself? Is there an option for that?

**Comment by TarekRaafat** [comment]
The input field is the easiest one because you can assign to it explicitly any `id/class` or even use inline styling.

You could easily just drop `autoComplete.js` style sheet and use your own and below are all the default programmed classes that you'd need for that.

```js
const select = {
  resultsList: "autoComplete_list",
  result: "autoComplete_result",
  highlight: "autoComplete_highlighted",
  selectedResult: "autoComplete_selected"
};
```
