### ISSUE TITLE
Browser compability detection

### ISSUE THREAD

**Issue by bbo2adwuff** [TarekRaafat/autoComplete.js#114]
Dear Tarek,

First of all a big thanks for this great package! 

**Is your feature request related to a problem? Please describe.**
I just had a user (with an old browser though...) complaining that my site is not working. :cry: 

**Thoroughly Describe the solution you'd like**
I would like to use a [feature detection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#Avoiding_user_agent_detection). 

**Please Describe alternatives you've considered**
One option would be to test for ES6, right? Haven't really thought it through, but this could be an option: https://gist.github.com/bendc/d7f3dbc83d0f65ca0433caf90378cd95

But as you know your code best, you probably have even better ideas for what would be an appropriate test?

**Comment by TarekRaafat** [comment]
Hello @bbo2adwuff,

I'm glad that it came in handy for you. :)

Sorry to hear that.

I would assume that that user was using IE11 or below because that is the only browser that's not supported.

Yet, you could use an easy online ES6 transpiler like [Babeljs.io's REPL](https://babeljs.io/repl) or [ES6 Console](https://es6console.com/) to solve the browser's backward compatibility issue. Still, you have to know what's broken for that user to be able to fix it while tuning the transpiler's settings.

Try giving it a shot and let me know how it went, I would always be glad to support you.


Cheers! :)
