### ISSUE TITLE
Make autoCompleteView module configurable

### ISSUE THREAD

**Issue by scarfacedeb** [TarekRaafat/autoComplete.js#118]
Would you consider making autoCompleteView module configurable during autoComplete initialization? It'll allow me to modify some rendering logic and keep most of your code in place.

## Use case

I need to render 2 lists of results from a single response. I reckoned that I'll be able to do that by creating a custom view module with modified `createResultsList` and ` addResultsToList` functions that would group the results by an arbitrary `type` key and render 2 lists instead of one.

If you're willing to consider such feature, I'll modify the code and create a PR.

**Comment by TarekRaafat** [comment]
Hello @scarfacedeb,

Sure, please do it's going to be very useful!


Cheers!

**Comment by Matoo125** [comment]
I'd be also interested in this. My goal is to display group labels that are not selectable in the list, such as in image below. Is this currently possible, or do I need to wait for an update?
![autocomplete](https://user-images.githubusercontent.com/10489019/85842116-7347f480-b79f-11ea-8f04-accf738ec20f.png)

**Comment by folknor** [comment]
Since autoComplete.js now provides `resultsList.container` and `const {input, query, matches, results} = data` in that function, this is now easily doable.

See https://github.com/TarekRaafat/autoComplete.js/issues/95#issuecomment-830598444 and https://github.com/TarekRaafat/autoComplete.js/issues/206#issuecomment-826828343 and possibly https://github.com/TarekRaafat/autoComplete.js/discussions/207 for some inspiration and pseudo/example code.
