### ISSUE TITLE
I see that only latest browsers are targetted, how about switching to flexbox for the css?

### ISSUE THREAD

**Issue by mikob** [TarekRaafat/autoComplete.js#12]
The css easily breaks if the input is not structured the same way you have in your example page. Flexbox is a nicer, simpler alternative for the autocomplete results IMO. Would you accept a PR making this change? 

Nice job with the library thus far btw! I like its simplicity!

**Comment by TarekRaafat** [comment]
I agree with you that's why I had on the [Roadmap](https://tarekraafat.github.io/autoComplete.js/#/?id=_6-roadmap) under "Usability" the Styles & Interactions are getting ongoing support in order to keep enhancing them and show new different designs for inspiration.

You're more than welcome please do!

Thank you so much, I'm glad you like it and hope it comes in handy for you.
