### ISSUE TITLE
Number autocomplete

### ISSUE THREAD

**Issue by andresfdel17** [TarekRaafat/autoComplete.js#132]
Hello, when i need autocomplete by number i have an error than says .lowercase() is not a function, please help me!

**Comment by TarekRaafat** [comment]
Hello @andresfdel17,

Sorry for my late feedback.

`autoComplete.js` lowercase the data, so it has to be `String` otherwise you get that error. 

The quick solution is turning the numbers into strings if this is not an issue or wait until it's fixed in [v8](https://github.com/TarekRaafat/autoComplete.js/tree/v8.0.0) by end of November.

Cheers, have a nice day! :)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
