### ISSUE TITLE
[docs] Trailing "> in the menu

### ISSUE THREAD

**Issue by Laegel** [TarekRaafat/autoComplete.js#148]
Hey there, nice library I just discovered. :+1: 
This is not a bug related to the lib itself but a minor issue on the docs website.
As I was taking a look at your docs, I saw that in the menu:

![image](https://user-images.githubusercontent.com/3584791/101284794-15a1e480-37e2-11eb-9403-295253fdb4d1.png)

Looks like your documentation framework doesn't appreciate `## [![autoComplete.js Code Example](./img/autoComplete.init.png "autoComplete.js Code Example")](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010)` when generating the menu!

I'm on Ubuntu 18.04, happens in Chromium and Firefox.

**Comment by TarekRaafat** [comment]
Hello @Laegel,

Thanks, I hope it comes in handy for you, and please let me know your feedback when you try it.

That issue has been annoying me for a couple of months, but unfortunately couldn't find enough time to debug it.
Now I've fixed it temporarily until I investigate it because it used to work fine previously.

Have a nice day. Cheers! :)
