### ISSUE TITLE
How best to share my integration with fuzzy string search libraries?

### ISSUE THREAD

**Issue by DustinWehr** [TarekRaafat/autoComplete.js#165]
I'm upgrading my app to use your project, due to the [`searchEngine` feature](https://github.com/TarekRaafat/autoComplete.js/issues/48), so that my app's autocomplete can benefit from the fuzzy string search that I'm already using elsewhere in the app. I have an interface over two fuzzy string search libraries, [Fuse](https://fusejs.io/) and [Fuzzball](https://github.com/nol13/fuzzball.js). 

Ideally, I would do this in such a way that others can easily benefit. A new item in [Third Party Plugins](https://tarekraafat.github.io/autoComplete.js/#/?id=_3-third-party-plugins) seems the obvious avenue, but 

1. I'm not sure about that, so I'm asking, and 
2. Even assuming the third party plugin option, I'm still unsure how best to combine the two, especially in terms of minimizing headaches due to future changes to autoComplete.js API (forgive me if the suggestion of breaking API changes is insulting!).

Here's one option: I publish my interface over Fuse and Fuzzball on github, and simply include in it a function that returns a `customEngine` function suitable for passing to autoComplete.js.

On another note: I would like to improve the documentation for the `searchEngine` feature at https://tarekraafat.github.io/autoComplete.js/#/?id=api-configuration, if that would be welcome. It's a bit confusing to me, even given https://github.com/TarekRaafat/autoComplete.js/issues/48#issuecomment-508185849. I'm wondering why `customEngine` doesn't return a boolean, in particular -- is it because we are free to return something other than the input `record` or `undefined`? The [source code](https://github.com/TarekRaafat/autoComplete.js/blob/b541d7b1b6a408576289881d8bfafffcf4f98f9c/src/controllers/dataController.js#L65) suggests that, but I'm not sure what the implications of doing so are. I suggest the API should be clear about whether that's supported.

Look forward to using your autocomplete. Happy New Years :-)

**Comment by TarekRaafat** [comment]
Hello @DustinWehr,


1. I agree with you, a [Third-Party Plugin](https://tarekraafat.github.io/autoComplete.js/#/?id=_3-third-party-plugins) would be the right option in your case
2. `searchEngine` API never changed since it was developed,  but it might see slight changes this year which will be communicated prior to and post the update as usual. Any API-breaking changes that might occur in the future won't affect your plugins as long as your sticking to the same version otherwise if you're looking forward to upgrading the version then you'll just update your plugin accordingly
3. Regarding the documentation of the `searchEngine` API please feel free to improve it, you're most welcome always to contribute to `autoComplete.js`

I hope I answered your questions clearly.

Please let me know if you have more questions or need further clarification.

Have a nice day and Happy New Year! :)
