### ISSUE TITLE
Can't use an array as data?

### ISSUE THREAD

**Issue by albu77** [TarekRaafat/autoComplete.js#17]
I try to use an array of string as data but it'snt recognized as such instance.data is an object 

![image](https://user-images.githubusercontent.com/624802/50615137-8f890f00-0ee3-11e9-9705-3a61bf5cb77b.png)
So I get an error when typing in :
autocomplete.min.js:1 Uncaught TypeError: Cannot read property 'filter' of undefined
    at t.value (autocomplete.min.js:1)
    at HTMLInputElement.<anonymous> (autocomplete.min.js:1)

**Comment by TarekRaafat** [comment]
The API has changed starting version 2.0.0, the data source goes into `data: { src: [array] }`, check the updated [How To Use](https://tarekraafat.github.io/autoComplete.js/#/?id=how-to-use) guide for more information.

Let me know how it goes.

```js
new autoComplete({
    data: { src: data, key: "food" },               // (Array, Object, Function, Async)
    placeHolder: "Food & Drinks...",                // Place Holder text
    selector: "#autoComplete",                      // Input field selector
    threshold: 0,                                   // Min. Chars length to start
    searchEngine: "strict",                         // Search Engine type/mode
    renderResults: {                                // Rendered results Destination & position
        destination: document.querySelector("#autoComplete"),
        position: "afterend"
    },
    highlight: true,                                // Highlight matching results
    dataAttribute: { tag: "set", value: "value" },  // Data attribute tag & value
    maxResults: 5,                                  // Max. number of rendered results
    onSelection: feedback => {                      // Action script onSelection event
        console.log(feedback);
    }
});
```

**Comment by albu77** [comment]
Ok, thanks.... so now it's working
Have a good year

**Comment by TarekRaafat** [comment]
Glad to help, you too have a good year! :)

**Comment by albu77** [comment]
Ok, it's working with an array of string but I don't get the way of working with such an array:
`{{"prod":"A.P De Villaine","id":0},{"prod":"Abbatucci","id":1},{"prod":"Agrapart","id":2},{"prod":"Alain Graillot","id":3},{"prod":"Alain Gras","id":4},{"prod":"Alex Gambal","id":5},{"prod":"Alice et Olivier De Moor","id":6}};`
Wher I would like to be able to get back the id when select in the list
On the other way I try to fork the codepen and replace your json url by test at http://www.restaurant-meursault.fr/lesProducteur.json and changing the key to "prod" but it didn't work either. I'm lost... if you could help

**Comment by TarekRaafat** [comment]
I've checked it, and obviously the "Access to fetch" from your source is being blocked by `CORS policy` because you're trying to fetch data from insecure source "[http](http://www.restaurant-meursault.fr/lesProducteur.json)" over secured source "[https](https://codepen.io/tarekraafat/pen/rQopdW)". So the data has to be served over secured source in order not to get blocked.

This is the `console.log` error message
```js
Mixed Content: The page at 'https://codepen.io/tarekraafat/pen/rQopdW?editors=1111' was loaded over HTTPS, but requested an insecure resource 'http://www.restaurant-meursault.fr/lesProducteur.json'. This request has been blocked; the content must be served over HTTPS.
```

My solution:
1- If your production server will not be secured serve data locally if possible, otherwise it should be fine
2- Use `Cross Origin Proxy` service (Not sure if suitable for production or not)
I'd recommend [CORS Anywhere](https://cors-anywhere.herokuapp.com/), you just have to add it's `URL` before your source link this way `https://cors-anywhere.herokuapp.com/http://www.restaurant-meursault.fr/lesProducteur.json` and it should be working fine for you.
