### ISSUE TITLE
Keyboard navigation not working

### ISSUE THREAD

**Issue by axlf** [TarekRaafat/autoComplete.js#182]
- [x] **System Information**
  - [x] Browser type and version: Chrome latest (88.0.*)
  - [x] Mac OS X 10.4.6

- [x] **Describe the bug**
I think keyboard navigation should work out of the box, but its not. At least not for me.

- [x] **To Reproduce**
I fiddled a basic example which won't work.

https://codepen.io/axlf/pen/RwoLeaV

Insert `iam`.
It should show the results. While trying to navigate with keyboard, nothing happens.

- [x] **Expected behavior**
Tabbing on arrow up or down should select the various options

- [x] **Screenshots or GIF's (optional, but HIGHLY RECOMMENDED)**
https://codepen.io/axlf/pen/RwoLeaV

**Comment by TarekRaafat** [comment]
Hello @axlf,

You've changed the `resultsList` container `id` value which misled the navigation event listener's pointer, and that's why it stopped working.

My bad, I should have made it clear to be avoided.


> Solution:

Don't change the `resultsList` container `id`.
Just remove the below `setAttribute` line.
```js
container: source => {
    source.setAttribute("id", "food_list");
},
```

Try it please and let me know how it went.

Cheers! :)

**Comment by axlf** [comment]
Thanks for your fast reply!

I'm not sure If I understand you correct.
When I remove the line, the result list won't show up.

**Comment by TarekRaafat** [comment]
The `resultsList` does not show up because it loses its position and falls down the page.

This happens due to the absence of the `autoComplete.js` container wrapper which is basically just an HTML `div` or `span` with a class of `class="autoComplete_wrapper"` as shown in this [demo](https://codepen.io/tarekraafat/pen/OJbxqPd?editors=1010).

Try it please and let me know how things went through.
