### ISSUE TITLE
Question: which is the best way of reloading the autocomplete data source ?

### ISSUE THREAD

**Issue by albu77** [TarekRaafat/autoComplete.js#19]
I would like to "refresh" the data when changes are brought to data coming from a database. Should I re instantiate the autoComplete or can I use some code to load the data src which updated data ?

**Comment by albu77** [comment]
A last thing for today: I think it would be smart if we could add a class to the results_list ul to avoid to duplicate code too much.

**Comment by TarekRaafat** [comment]
@albu77 is there any event occurs on data update in the front-end layer?

Regarding adding class to the `results_list` `ul`,  you can achieve that as shown below.

```js
resultsList: {
  container: source => {
    source.classList.add("manufacturers_List");
  };
}
```

**Comment by TarekRaafat** [comment]
@ronbrun this behavior happens because `autoComplete.js` caches the `data src` as soon as you instantiate it, and it reads data from the cached `data src` for faster performance during usage. That's why when you update the `data src` it doesn't reflect changes in the results until you re-instantiate the `autoComplete.js` to load/fetch the updated data.

I'm currently exploring some different ideas on updating the cached `data src` on data change, but it might not be so practical in case the data source is external.

Still you can find many workarounds until I find a proper solution for it.

**Comment by TarekRaafat** [comment]
@albu77 sorry for my late reply, I have been very busy recently.

All what I can think of right now is the option you've suggested previously "Re-instantiating" `autoComplete` on data change event.

Will definitely get back to you if I found other solutions for it.

Cheers! :)
