### ISSUE TITLE
Why was sort removed?

### ISSUE THREAD

**Issue by folknor** [TarekRaafat/autoComplete.js#200]
In https://github.com/TarekRaafat/autoComplete.js/commit/6d04d41dbcf539cb03c52adf67671a8794f8f50e you removed `sort`, and I can't find an open or closed issue or discussion that explains why.

Also the commit message has no information on why.

We use autocomplete to for example complete street addresses including house number, and we don't control the REST server and it returns results in an order we can't determine.

In autocomplete 8.x we just used `sort`, what should we do now?

Should we just sort before we return from data:src?

**Comment by TarekRaafat** [comment]
Hello @folknor,

`sort` API was removed because it became redundant eventually due to the existence of [`data.results`](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=data-required) which is much more flexible than `sort` because it covers a wide range of different use cases including sorting.

So, don't worry you could easily achieve the exact same sorting results as before even with better performance using the [`data.results`](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=data-required) API as used in the demo [code](https://github.com/TarekRaafat/autoComplete.js/blob/master/dist/js/index.js#L16-L20) for filtering duplicate values.

All you have to do is just moving your sorting algorithm inside `data.results` and apply the needed changes.


Please try it and let me how it goes.

Have a nice day! :)

**Comment by folknor** [comment]
Thanks I will try it tomorrow :-) Perhaps point to `data.results` in the changelog text.

**Comment by TarekRaafat** [comment]
```js
data: {
  results: (list) => {
    return list.sort((a, b) => {
      if (a.match < b.match) return -1;
      if (a.match > b.match) return 1;
      return 0;
    }
  }
}
```
