### ISSUE TITLE
Useless code?

### ISSUE THREAD

**Issue by showmeyourhits** [TarekRaafat/autoComplete.js#23]
Hi.
I have been reading your source code, and came across [this line](https://github.com/TarekRaafat/autoComplete.js/blob/master/src/models/autoComplete.js#L145).

Could you, please, explain what does it do?
Do you know some hidden JS knowledge, or not? Because it seems, that this line doesn't do anything.

**Comment by TarekRaafat** [comment]
Hello @showmeyourhits,

Thanks for taking the time to go through the source code.

That line was meant to clear the results list for the search engine previously, because the search engine at early days didn't clear it automatically which is not the case anymore. I just forgot to remove it after redesigning the search engine.

Thank you for your good notice, i've removed that line already in the last commit.

Never heard of "Hidden JS" but I read about it a little bit after you mentioned it in your comment, but couldn't relate what use case are you referring to use it for?

Cheer! :)

**Comment by showmeyourhits** [comment]
I forgot to mention, that there is same line in `else` block. [Here it is](https://github.com/TarekRaafat/autoComplete.js/blob/79dfcc4ac380c777b295dc4b70912ac4437ffffc/src/models/autoComplete.js#L153). 

I think, code that clears result list is on [line #141](https://github.com/TarekRaafat/autoComplete.js/blob/79dfcc4ac380c777b295dc4b70912ac4437ffffc/src/models/autoComplete.js#L141).

But what code on line #153 do?

**Comment by TarekRaafat** [comment]
Line [#153](https://github.com/TarekRaafat/autoComplete.js/blob/79dfcc4ac380c777b295dc4b70912ac4437ffffc/src/models/autoComplete.js#L153) in the `else` block is responsible for clearing the results list when the `input` field is empty.

Line [#141](https://github.com/TarekRaafat/autoComplete.js/blob/79dfcc4ac380c777b295dc4b70912ac4437ffffc/src/models/autoComplete.js#L141) is holding the `clear` function value to be used later as on line [#153](https://github.com/TarekRaafat/autoComplete.js/blob/79dfcc4ac380c777b295dc4b70912ac4437ffffc/src/models/autoComplete.js#L153).
