### ISSUE TITLE
Returning an error from data.src triggers exception

### ISSUE THREAD

**Issue by folknor** [TarekRaafat/autoComplete.js#234]
In the official codepen playground and other places you have this code now:
```js
src: async () => {
      try {
        return data;
      } catch (error) {
        return error;
      }
}
```
But if this errors, autoComplete.js triggers an exception:
```
19:08:26.990 Uncaught (in promise) TypeError: data.store.forEach is not a function
    findMatches dataController.js:36
    default index.f58c4ea9.js:22807
    run eventController.js:27
    timer io.js:89
    setTimeout handler*debounce/< io.js:89
    input eventController.js:41
    addEvents eventController.js:71
    eventsManager eventController.js:14
    addEvents eventController.js:70
    default index.f58c4ea9.js:22471
    autoComplete autoComplete.js:37
    init index.f58c4ea9.js:1261
```

Because in start.js or `findMatches` you never validate that it didn't error.

Also on a sidenote, I don't think `cache` is working at the moment (though I believe the cache should be removed anyway), because you never set `data.cache` anywhere:
```
$ pwd
/home/folk/.../node_modules/@tarekraafat/autocomplete.js/src
$ rg '.cache'
services/init.js
48:  if (data.cache) await getData(ctx);

controllers/dataController.js
12:  if (data.cache && data.store) return;
```

**Comment by folknor** [comment]
Also https://github.com/TarekRaafat/autoComplete.js/blob/7e1930626ae8cc9a8ac90fd3aac4fdf31202866b/src/autoComplete.js#L38 is wrong. I had not tried it when I wrote that, it should say something like "Makes the Tab key select the entry navigated to using the keyboard, just like Enter."

`config.data.filter` should perhaps say "Used to filter and sort matching returns from config.data.src before showing them to the user. Signature: (Array), is given all the results from config.data.src that matches the query."

**Comment by TarekRaafat** [comment]
You're correct about the `Error` behavior which I was planning to handle at some point and I guess I'll fix it today.

The `data.cache` is made to fetch the data only one time and store it inside the `data.store`, for the cases where you don't need to keep fetching the data for each `query`.

For example, using this API `https://restcountries.eu/rest/v2/region/europe` one call retrieves all the required data so you don't need to repeat the API call.

Regarding the data storage, you'll need to connect the `autoComplete.js` `data.store` to whichever storing method that you're using otherwise the data will only be persistent until the page reloads which is still data caching but short-term/temp caching.

I hope I got your points correctly, if not please clarify.

Thanks for the correction, I've updated it! 👍

**Comment by folknor** [comment]
> You're correct about the `Error` behavior which I was planning to handle at some point and I guess I'll fix it today.

No rush! The way you fixed it in 10.1.2 seems a bit strange to me because the error is still just silently ignored. I mean I handle it myself now by doing it "outside" the autoComplete.js data structure, but I thought the plan was to expose it in some official way after your last comment in https://github.com/TarekRaafat/autoComplete.js/discussions/207

Again there is no rush, but when I saw the example `try..catch` code in the docs after v10 was released, I thought maybe you had coded some solution for it :-) And when I tested it and it generated an error I thought it was best to let you know.

One solution could be to get a reference to the error object in `resultsList.element`, like `const { input, query, matches, results, error } = data` or something. And perhaps a new boolean property like `resultsList.error` or `.showError` or something to make the list open when there is an error at all.

Does that make sense?

Anyway you probably have a better idea, and the code I have now (like in the linked discussion) is working so no worries.

> The `data.cache` is made to fetch the data only one time and store it inside the `data.store`, for the cases where you don't need to keep fetching the data for each `query`.

Ah I see it now, silly me! Thank you.

**Comment by TarekRaafat** [comment]
Thank you for following up on the `error` point! :)

Frankly, that's how I was planning to handle errors because if it's going to be limited to the list, then in case you're not using the default rendered list for some reason you won't be able to catch them and use them.
So, the current way of getting the `error` from the `feedback` or `data.store` seems to be the most flexible for most use cases.

Yet, there could be a better way, but I guess we need to try it first and see how it plays out in real-life scenarios.

**Comment by folknor** [comment]
I think I misunderstand your last comment. I'm not really able to parse and understand what you said :-P

Anyway it could be as simple as changing start.js from
```js
    // Check if data fetch failed
    if (ctx.feedback instanceof Error) return;
    // Find matching results to the query
    findMatches(queryVal, ctx);
    // Render "resultsList"
    if (resultsList) render(ctx);
```
to
```js
    if (ctx.feedback instanceof Error) {
      if (resultsList && resultsList.element && resultsList.showError) {
        ctx.cursor = -1;
        ctx.list.innerHTML = "";
        resultsList.element(ctx.list, feedback);
        open(ctx);
      }
    } else {
      // Find matching results to the query
      findMatches(queryVal, ctx);
      // Render "resultsList"
      if (resultsList) render(ctx);
    }
```

I realise it looks dirty. Also I've not tested it, and start.js needs to import `open` from listController. And if I was going to implement it "properly" I'd move this logic to listController, probably adding a `reset` function there for resetting .cursor and .innerHTML and so forth.

Anyway again I don't really understand your previous comment so if this comment is useless please excuse me. I do understand that the error is in `feedback` and `data.store`, but not the sentence before that - this one:

> Frankly, that's how I was planning to handle errors because if it's going to be limited to the list, then in case you're not using the default rendered list for some reason you won't be able to catch them and use them.
