### ISSUE TITLE
resultlist order loose mode

### ISSUE THREAD

**Issue by kasperkamperman** [TarekRaafat/autoComplete.js#260]
Is there a way to sort the resultList order?

I'm using loose mode, I'm getting this result if I type "nij". 

![Screenshot 2021-07-20 at 21 26 41](https://user-images.githubusercontent.com/1760616/126384567-434b8227-b34c-4be7-a6b1-4d21392db541.png)

I would prefer that the items that have the exact character sequence appear on the top of the list and alphabetically. At least that seems more logical to me. 

I'd like to keep using loose because it works great with some more complex names like **'s-Hertogenbosch**. (sorry place names in Dutch 😁 ). 

Thanks for the customization options, I'm using Bulma for styling.

**Comment by folknor** [comment]
Yes.

You can use `config.data.filter`, like for example:

```js
data: {
	src: ...,
	keys: ...,
	filter: list => {
		if (list.length < 5) {
			return list
		}
		const q = document.getElementById("search").value.toLowerCase()
		return list.sort((first, second) => {
			let fs = diceCoefficient(
				q,
				first.value.name.toLowerCase()
			)
			let ss = diceCoefficient(
				q,
				second.value.name.toLowerCase()
			)
			if (fs === ss) {
				return first.value.name > second.value.name
			}
			return ss > fs
		})
	}
},
```
(code edited for publication, obviously sanitize user input)

The only "problem" with `config.data.filter` is that there's no access to the modified query (as modified by `config.query`).

@TarekRaafat Might be an idea to add the query and other context as arguments to the function, like `resultItem.element` and `resultsList.element`.

**Comment by kasperkamperman** [comment]
@folknor I tried your code (modified ```document.getElementById('autoComplete').value.toLowerCase()```) but I get the response: ```diceCoefficient is not defined```. 

@TarekRaafat To me it seems like a bug. That the results that are the least relevant are on top of the list. 
It would be more logical that the exact character sequence is on top and then the character sequence that is loose. 

I love the loose mode over strict mode (because Dutch place names have some strange characters, so with loose mode you can skip them and still the right result appears). 

I think the best in loose mode is that strict results should appear first and then the loose results.

**Comment by kasperkamperman** [comment]
@TarekRaafat Thanks to your example (https://tarekraafat.github.io/autoComplete.js/#/how-to-guides?id=example-5) I could grasp how it worked. 

This is the filter I ended up building:

```
 filter: list => {

    // sort result list alfabetically
    list.sort((a,b) => {
        return b.match.localeCompare(a.match);
    });
    
    // no need to continue if we have less then the maxResults variable
    if (list.length < autoCompleteJS.resultsList.maxResults) {
        return list;
    }
    
    list.sort((item) => {
        const inputValue = autoCompleteJS.input.value.toLowerCase();
        const itemValue = item.match.toLowerCase();
    
        if (itemValue.startsWith(inputValue)) {
            return -1;
        }
        return 1;
    
    });
    
    return list;
    
}

```
Hope it helps someone that runs in this in the future.

**Comment by TarekRaafat** [comment]
Hello @kasperkamperman,

> @folknor I tried your code (modified document.getElementById('autoComplete').value.toLowerCase()) but I get the response: diceCoefficient is not defined.

You're getting the above-mentioned error because '[diceCoefficient](https://www.npmjs.com/package/dice-coefficient)`, a library that measures the distance between two different strings, does not exist within your project, so you need to add it to your project for @folknor's example to work.

> @TarekRaafat To me it seems like a bug. That the results that are the least relevant are on top of the list.
It would be more logical that the exact character sequence is on top and then the character sequence that is loose.

I get where you're coming from, but surprisingly not every project's requirements would be the same. So we can't be certain that restricting the default sorting order as you're suggesting would suit most of the use cases. That's why there's the `filter` API to give the developer control over data manipulation and sorting before display.

> @TarekRaafat Thanks to your example (https://tarekraafat.github.io/autoComplete.js/#/how-to-guides?id=example-5) I could grasp how it worked.

I'm glad that the `How-to Guides` section was useful for you, and I would suggest that you install '[diceCoefficient](https://www.npmjs.com/package/dice-coefficient)` and try @folknor's solution it should give you tighter results.


Cheers, and have a nice day! :)
