### ISSUE TITLE
Improving perf for large datasets

### ISSUE THREAD

**Issue by Johann-S** [TarekRaafat/autoComplete.js#28]
Hi @TarekRaafat,

I use your last release (4.0.0) on a large data set (5358 elements) and my browser totally freeze 😟 
According to your browser support it'll be awesome if you can wrap your search logic in a Promise and resolve when it's done, it'll avoid that side effect.

What do you think about that ? 

Thanks again for your plugin 👍

**Comment by TarekRaafat** [comment]
Hello @Johann-S,

Thanks for reporting that behavior!

I will test it and check that behavior on larger datasets as well, initially your solution sounds really good, but I'll have to check the root cause first and solve it before taking your path.

Will let you know as soon as I find the root cause and a solution for it.

Cheers! :)

**Comment by Johann-S** [comment]
Thanks @TarekRaafat for considering my issue 👍 
BTW if you need a sample of data, I can export one
