### ISSUE TITLE
Something wrong with the demo?

### ISSUE THREAD

**Issue by leesmith** [TarekRaafat/autoComplete.js#29]
I can reproduce this in Firefox as well as Chrome...gif is from Firefox. Or maybe I don't understand the demo? Thanks!

![autocomplete](https://user-images.githubusercontent.com/90055/54211532-7dad8480-44af-11e9-86de-fbf04f416094.gif)

**Comment by TarekRaafat** [comment]
Hello @leesmith,

The rendered results in the list are coming out of different keys as shown in the `API` below, so that they are mixed between `["food", "cities", "animals"]`.

The rendered selection is just single key which is `food` as in the demo which was `Garam Masala Powder` that comes from an object with `animal` value of `Starling, red-shouldered glossy`.

So if you checked the logged selection in the `console.log` you should find the original selected value in that object.

You can change the rendered selection as you may like based on your needs, it's totally up to you.

Hope I answered your question.

```js
new autoComplete({
    data: {                              // Data src [Array, Function, Async] | (REQUIRED)
        src: data,
        key: ["food", "cities", "animals"]
    },
    sort: (a, b) => {                    // Sort rendered results ascendingly | (Optional)
        if (a.match < b.match) return -1;
        if (a.match > b.match) return 1;
        return 0;
    },
    placeHolder: "Food & Drinks...",     // Place Holder text                 | (Optional)
    selector: "#autoComplete",           // Input field selector              | (Optional)
    threshold: 0,                        // Min. Chars length to start Engine | (Optional)
    searchEngine: "strict",              // Search Engine type/mode           | (Optional)
    resultsList: {                       // Rendered results list object      | (Optional)
        container: source => {
            resultsListID = "food_List";
            return resultsListID;
        },
        destination: document.querySelector("#autoComplete"),
        position: "afterend"
    },
    resultItem: (data, source) => {        // Rendered result item            | (Optional)
        return `${data.match}`;
    },
    highlight: true,                       // Highlight matching results      | (Optional)
    maxResults: 5,                         // Max. number of rendered results | (Optional)
    onSelection: feedback => {             // Action script onSelection event | (Optional)
        console.log(feedback);
    }
});
```

**Comment by leesmith** [comment]
Perfect. Thanks!

**Comment by gilbertoalbino** [comment]
Demo doesn't work for me on any browser.

**Comment by TarekRaafat** [comment]
Hello @gilbertoalbino,

Which demo are you referring to?

**Comment by gilbertoalbino** [comment]
@TarekRaafat  the one provided in the readme.
https://tarekraafat.github.io/autoComplete.js/demo/

**Comment by TarekRaafat** [comment]
@gilbertoalbino I've been checking it regularly since I released the new version and I just did now and it's working for me.

Could you please check the console logs and let me know if you're getting any kind of errors or not, and I would like to know what browser you're using and what version as well.

**Comment by ankane** [comment]
This confused me as well fwiw (thought the library buggy). It might be more intuitive to show the item that was selected.

**Comment by TarekRaafat** [comment]
Hello @ankane,

I'm glad you found this issue! :sweat_smile:

You're right. I agree with you. I'll change that behavior.


Cheers! :thumbsup:
