### ISSUE TITLE
Default results

### ISSUE THREAD

**Issue by beamercola** [TarekRaafat/autoComplete.js#35]
is it possible to show an "empty" state search, for instance i'd be putting "recent searches", then when they start typing it swaps them out.

or even better yet, have a persistent list so I can have Recent and Results in the same box.

if this was possible, i'd be ecstatic

**Comment by TarekRaafat** [comment]
Hello @beamercola,

Sorry for my late feedback.

All the proposed ideas are very nice indeed, and could be done on top of the library as a plugin or customization instead of implementing them directly in the core library itself for the following reasons:

1- Not core functions/features
2- Not frequently used/requested
3- These functions/features might get very subjective in the way they could be built and used in

I hope you understand my point of view, and i'm always open for discussions.

Thank you, have a good weekend! :)
