### ISSUE TITLE
Do you planning to add async loading of gloccery?

### ISSUE THREAD

**Issue by Tankerxyz** [TarekRaafat/autoComplete.js#4]
Not always we have all gloccery right now on front-end side. Sometimes It's a big data, maybe stored into elasticsearch or some. Do you planning to add async loading chunk of result data?

**Comment by Tankerxyz** [comment]
I can think about this implementation, If you don't mind :)

**Comment by TarekRaafat** [comment]
Please do, you're more than welcome!

Actually it was on the roadmap as an "[External data source `(Plugin)`](https://github.com/TarekRaafat/autoComplete.js/blob/master/README.md)" as a plugin, because the way developers might load data from external source could be very subjective, let alone that it would overload the library.

I would really love to know how would you implement it without being opinionated or overloading the library.

**Comment by Tankerxyz** [comment]
I think about giving "dataSrc" as async function that can loading some data and return array. 
Loading and normalizing data will coded by user into callback. All we need it's implement checking if async function was given as a dataSrc parameter and wait returned data, afterthat do other actions with this list. While function load some data, we can show the loader, or a custom element given by user. I need to think about that.

**Comment by Tankerxyz** [comment]
I think about giving "dataSrc" as async function that can loading some data and return array.
Loading and normalizing data will coded by user into callback. All we need it's implement checking if async function was given as a dataSrc parameter and wait returned data, afterthat do other actions with this list. While function load some data, we can show the loader, or a custom element given by user. I need to think about that.

**Comment by Tankerxyz** [comment]
I create the pull-request when I have done.
