### ISSUE TITLE
Intercept user input before searching

### ISSUE THREAD

**Issue by barns101** [TarekRaafat/autoComplete.js#45]
Great library, thank you so much for creating it!

I have a feature request: I would like to intercept the user input before a search is performed.

My initial use case is that I want to remove "_The_" from the start of a search string.

Setting an optional config method called "beforeSearch" that takes the user's input string and returns another string would be ideal.

```
beforeSearch: (userInput) => { // Modify the search string | (Optional)
  // Do something with the user's input
  // const searchValue = userInput.replace("The ", "");
  // return searchValue;
}
```

So "_The Eiffel Tower_" becomes "_Eiffel Tower_" etc...

I guess you could also use it to log search strings to do analysis on what searches are popular etc...

Thanks!

**Comment by TarekRaafat** [comment]
Hello @barns101,

I'm so glad you like it!

I really like your idea "Intercepting & Modifying user's query" and I find it very useful.

I'll start working on it this week to make sure that it will be added to next weekend release.

Will let you know when I finish it in order to test it before releasing it.

Thanks a lot for your request, have a good day.

Cheers! :)

**Comment by TarekRaafat** [comment]
I've added it in my last commit find it in the below `Demo` link, kindly test it and let me know if there is anything that needs to be changed or tweaked.

[Demo Folder](https://github.com/TarekRaafat/autoComplete.js/tree/master/dist)

**Comment by barns101** [comment]
Hi Tarek. Thank you for adding it so quickly.

There's some unexpected behaviour: when I search for "pizza" I get the full list of results back. I would expect that as soon as I type the last "a" in "pizza" and the string is replaced with and empty string I would get no results, because the search engine does not accept an empty string.

I hope that makes sense.

![image](https://user-images.githubusercontent.com/8156375/59159285-5589ed80-8abf-11e9-98a0-4e86e8604282.png)

**Comment by TarekRaafat** [comment]
Hello @barns101,

I've fixed it now. It turned out that I forgot to remove extra space after the `query` that's why you got that weird behavior.

I guess it should be working fine as expected now, please try it and let me know your thoughts.

[Demo](https://github.com/TarekRaafat/autoComplete.js/tree/master/dist)

**Comment by barns101** [comment]
Ah yes that makes sense!

Working perfectly now. Thank you!

**Comment by TarekRaafat** [comment]
Anytime! :)

**Comment by TarekRaafat** [comment]
Hello @barns101,

The check out the new release [v6.0.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v6.0.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/npm/@tarekraafat/autocomplete.js)

Let me know your thoughts.

Have a good day, cheers! :)

**Comment by barns101** [comment]
Working perfectly! Thank you for incorporating this feature!
