### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by srinivas025** [TarekRaafat/autoComplete.js#71]
Hi, thanks for the great library.
I am facing this issue when i use fetch("").then() instead of async/await inside data.src function
```
fetch("apicall?search="+query)
     .then(r =>  r.json().then(data => ({status: r.status, body: data})))
     .then(obj => {
      return obj.results;
 });
```
can you please tell me how can i use .then() without seeing the above mentioned error.
Thanks

**Comment by TarekRaafat** [comment]
Hello @srinivas025,

Could you please provide the below details to help solve your issues quickly, we need you to make a best effort to complete the information below. Any incomplete bug reports will be closed.


- [ ] **System Information**
  - [ ] Browser type and version
  - [ ] OS type and version
  - [ ] WINDOWS: be sure to indicate which terminal you're using -- (i.e., cmd.exe, powershell, git- bash, cygwin, Ubuntu via windows subsystem for linux, etc...)
  - [ ] Node version (IF applicable)
    - [ ] Any error messages that may be in the console where you ran npm start
  - [ ] Any error messages in the JS console

- [ ] **Describe the bug**


- [ ] **To Reproduce**
Steps to reproduce the behavior: <!-- Example below-!>
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

- [ ] **Expected behavior**
A clear and concise description of what you expected to happen.

- [ ] **Screenshots or GIF's (optional, but HIGHLY RECOMMENDED)**
If applicable, add screenshots to help explain your problem.

- [ ] **Additional context (optional)**
Add any other context about the problem here.
